name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: ['', 'extended']
    steps:
      - run: echo ${{ matrix.tags }}

  use:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        version: ['1', '2', '3']
    steps:
      - run: echo ${{ matrix.version }}
